//SESSIONS ACTIONS
export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

//REGISTRATION ACTIONS
export const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
export const UPDATE_SHOW_FORM_MODAL = 'UPDATE_SHOW_FORM_MODAL';
export const UPDATE_SHOW_EMAIL_CONFIRMATION_MODAL = 'UPDATE_SHOW_EMAIL_CONFIRMATION_MODAL';
export const RESET_PAGE = 'RESET_PAGE';
export const REGISTER_AS_CONSUMER = "REGISTER_AS_CONSUMER";
export const REGISTER_AS_STYLIST = "REGISTER_AS_STYLIST";

//LOGIN ACTIONS
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_ERROR = 'UPDATE_ERROR';