//USER ACTIONS
export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_OUT = 'LOG_USER_OUT';
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
export const CHANGE_USER_TOKEN = 'CHANGE_USER_TOKEN';

//REGISTRATION ACTIONS
export const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
export const UPDATE_IS_REGISTERED = 'UPDATE_IS_REGISTERED';
export const UPDATE_SHOW_FORM_MODAL = 'UPDATE_SHOW_FORM_MODAL';
export const UPDATE_SHOW_EMAIL_CONFIRMATION_MODAL = 'UPDATE_SHOW_EMAIL_CONFIRMATION_MODAL';
export const RESET_PAGE = 'RESET_PAGE';

//LOGIN ACTIONS
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_ERROR = 'UPDATE_ERROR';